# Create geographical base file

This script loads a bunch of official GIS data and creates a single file that shows:

- Which bidding zones a municipality belongs to and to which extent
- Which region a municipality belongs to
- Which federation a municipality belongs to

It contains both codes and clear text values.

In [1]:
# Import libraries and set basic variables

import sys
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
from pathlib import Path

root_path = Path(globals()['_dh'][0]).resolve().parent.parent.parent
sys.path.append(str(root_path))

from paths import input_path
from generator.library.utilities import get_path

In [7]:
## This data has been taken from the source code of nätområden.se
## It has been cleaned up (delete a property with html code) and stored as a geojson file

biddingzones = gpd.read_file("biddingzones.geojson", encoding='utf-8')

## The data below is an unofficial version of Sweden's municipalities taken from Opendatasoft

municipalities = gpd.read_file("georef-sweden-kommun@public.geojson", encoding='utf-8')

## Reproject the two frames to get accurate areas
municipalities = municipalities.to_crs(epsg=3006)
biddingzones = biddingzones.to_crs(epsg=3006)

Skipping field center: unsupported OGR type: 3

In [15]:
# Calculate

# Perform spatial intersection to find overlapping areas
intersection = gpd.overlay(municipalities, biddingzones, how='intersection')

# Add a column for the area of the intersected geometry
intersection['intersected_area'] = intersection.geometry.area

# Add a column for the original municipality's total area
municipalities['total_area'] = municipalities.geometry.area

# Merge intersected GeoDataFrame with municipalities' total area using kom_code
intersection = intersection.merge(
    municipalities[['kom_code', 'total_area']],
    left_on='kom_code',
    right_on='kom_code',
    suffixes=('', '_muni')
)

# Calculate the percentage area of each municipality in each bidding zone
intersection['percentage_area'] = (intersection['intersected_area'] / 
                                    intersection['total_area'])

In [16]:
intersection.loc[intersection['kom_name'] == 'Arjeplog']

,geo_point_2d,year,lan_code,lan_name,kom_code,kom_name,kom_area_code,kom_type,total_area,omr,namn,bolag,snitt,id,geometry,intersected_area,total_area_muni,percentage_area
0,"{ ""lon"": 17.239017732460756, ""lat"": 66.3645005...",2022,25,Norrbottens län,2506,Arjeplog,SWE,Kommun,1.458153e+10,None,SE2,None,2,SE2,"POLYGON ((520428.91 7358424.673, 520441.02 735...",3.017875e+03,1.458153e+10,2.069657e-07
1,"{ ""lon"": 17.239017732460756, ""lat"": 66.3645005...",2022,25,Norrbottens län,2506,Arjeplog,SWE,Kommun,1.458153e+10,None,SE1,None,1,SE1,"POLYGON ((527543.431 7386296.07, 530038.181 73...",1.358218e+10,1.458153e+10,9.314648e-01

In [17]:
intersection[intersection['kom_code'].duplicated(keep=False)]

,geo_point_2d,year,lan_code,lan_name,kom_code,kom_name,kom_area_code,kom_type,total_area,omr,namn,bolag,snitt,id,geometry,intersected_area,total_area_muni,percentage_area
0,"{ ""lon"": 17.239017732460756, ""lat"": 66.3645005...",2022,25,Norrbottens län,2506,Arjeplog,SWE,Kommun,1.458153e+10,None,SE2,None,2,SE2,"POLYGON ((520428.91 7358424.673, 520441.02 735...",3.017875e+03,1.458153e+10,2.069657e-07
1,"{ ""lon"": 17.239017732460756, ""lat"": 66.3645005...",2022,25,Norrbottens län,2506,Arjeplog,SWE,Kommun,1.458153e+10,None,SE1,None,1,SE1,"POLYGON ((527543.431 7386296.07, 530038.181 73...",1.358218e+10,1.458153e+10,9.314648e-01
9,"{ ""lon"": 12.243643323264264, ""lat"": 57.1579433...",2022,13,Hallands län,1383,Varberg,SWE,Kommun,1.710687e+09,None,SE4,None,4,SE4,"POLYGON ((358504.171 6344993.838, 357916.61 63...",3.153454e+04,1.710687e+09,1.843385e-05
10,"{ ""lon"": 12.243643323264264, ""lat"": 57.1579433...",2022,13,Hallands län,1383,Varberg,SWE,Kommun,1.710687e+09,None,SE3,None,3,SE3,"POLYGON ((321581.693 6356717.101, 323347.144 6...",1.006077e+09,1.710687e+09,5.881128e-01
23,"{ ""lon"": 16.377957613599087, ""lat"": 61.3125715...",2022,21,Gävleborgs län,2183,Bollnäs,SWE,Kommun,1.987929e+09,None,SE2,None,2,SE2,"POLYGON ((555643.674 6780200.052, 556246.648 6...",1.788450e+09,1.987929e+09,8.996552e-01
24,"{ ""lon"": 16.377957613599087, ""lat"": 61.3125715...",2022,21,Gävleborgs län,2183,Bollnäs,SWE,Kommun,1.987929e+09,None,SE3,None,3,SE3,"POLYGON ((591100.968 6782061.786, 590835.244 6...",8.013409e+08,1.987929e+09,4.031034e-01
26,"{ ""lon"": 13.804976625081229, ""lat"": 57.3560733...",2022,06,Jönköpings län,0617,Gnosjö,SWE,Kommun,4.514935e+08,None,SE4,None,4,SE4,"MULTIPOLYGON (((430460.565 6347382.572, 430506...",3.359955e+07,4.514935e+08,7.441869e-02
27,"{ ""lon"": 13.804976625081229, ""lat"": 57.3560733...",2022,06,Jönköpings län,0617,Gnosjö,SWE,Kommun,4.514935e+08,None,SE3,None,3,SE3,"POLYGON ((415888.714 6362102.114, 416128.975 6...",5.244949e+07,4.514935e+08,1.161689e-01
39,"{ ""lon"": 15.801347438463512, ""lat"": 57.3986937...",2022,08,Kalmar län,0860,Hultsfred,SWE,Kommun,1.195258e+09,None,SE4,None,4,SE4,"POLYGON ((562929.923 6353022.814, 562838.287 6...",3.030428e+08,1.195258e+09,2.535375e-01
40,"{ ""lon"": 15.801347438463512, ""lat"": 57.3986937...",2022,08,Kalmar län,0860,Hultsfred,SWE,Kommun,1.195258e+09,None,SE3,None,3,SE3,"POLYGON ((531301.156 6361165.388, 531296.954 6...",6.799645e+08,1.195258e+09,5.688850e-01
53,"{ ""lon"": 14.716151367087592, ""lat"": 61.3179142...",2022,20,Dalarnas län,2034,Orsa,SWE,Kommun,1.804354e+09,None,SE2,None,2,SE2,"MULTIPOLYGON (((498283.478 6817749.426, 498796...",1.439030e+07,1.804354e+09,7.975318e-03
54,"{ ""lon"": 14.716151367087592, ""lat"": 61.3179142...",2022,20,Dalarnas län,2034,Orsa,SWE,Kommun,1.804354e+09,None,SE3,None,3,SE3,"POLYGON ((482803.774 6828680.871, 482950.513 6...",1.804354e+09,1.804354e+09,1.000000e+00
72,"{ ""lon"": 13.703325416757052, ""lat"": 62.2128361...",2022,23,Jämtlands län,2361,Härjedalen,SWE,Kommun,1.192102e+10,None,SE2,None,2,SE2,"POLYGON ((393209.061 6890682.568, 390821.459 6...",1.038765e+10,1.192102e+10,8.713721e-01
73,"{ ""lon"": 13.703325416757052, ""lat"": 62.2128361...",2022,23,Jämtlands län,2361,Härjedalen,SWE,Kommun,1.192102e+10,None,SE3,None,3,SE3,"MULTIPOLYGON (((406907.945 6879988.914, 403643...",1.657559e+09,1.192102e+10,1.390450e-01
80,"{ ""lon"": 20.84844950948122, ""lat"": 64.75236043...",2022,24,Västerbottens län,2482,Skellefteå,SWE,Kommun,1.001056e+10,None,SE2,None,2,SE2,"POLYGON ((771481.821 7146080.067, 770836.285 7...",8.799888e+08,1.001056e+10,8.790607e-02
81,"{ ""lon"": 20.84844950948122, ""lat"": 64.75236043...",2022,24,Västerbottens län,2482,Skellefteå,SWE,Kommun,1.001056e+10,None,SE1,None,1,SE1,"POLYGON ((756275.731 7144229.562, 756446.28 71...",6.713637e+09,1.001056e+10,6.706556e-01
82,"{ ""lon"": 14.580986389129738, ""lat"": 57.3278380...",2022,06,Jönköpings län,0684,Sävsjö,SWE,Kommun,7.324444e+08,None,SE4,None,4,SE4,"POLYGON ((488340.39 6350159.072, 488353.085 63...",2.559355e+08,7.324444e+08,3.494265e-01
83,"{ ""lon"": 14.580986389129738, ""lat"": 57.3278380...",2022,06,Jönköpings län,0684,Sävsjö,SWE,Kommun,7.324444e+08,None,SE3,None,3,SE3,"MULTIPOLYGON (((462552.53 6367817.34, 462831.3...",5.812911e+07,7.324444e+08,7.936317e-02
104,"{ ""lon"": 13.507763937118506, ""lat"": 57.2541137...",2022,06,Jönköpings län,0662,Gislaved,SWE,Kommun,1.223520e+09,None,SE4,None,4,SE4,"POLYGON ((422093.667 6347440.432, 422600.569 6...",7.157022e+08,1.223520e+09,5.849533e-01
105,"{ ""lon"": 13.507763937118506, ""lat"": 57.2541137...",2022,06,Jönköpings län,0662,Gislaved,SWE,Kommun,1.223520e+09,None,SE3,None,3,SE3,"MULTIPOLYGON (((402885.748 6356430.566, 403398...",2.724912e+08,1.223520e+09,2.227109e-01
125,"{ ""lon"": 19.513815414031246, ""lat"": 64.3561377...",2022,24,Västerbottens län,2404,Vindeln,SWE,Kommun,2.871493e+09,None,SE2,None,2,SE2,"POLYGON ((706817.599 7187326.028, 708700.677 7...",2.871493e+09,2.871493e+09,1.000000e+00
126,"{ ""lon"": 19.513815414031246, ""lat"": 64.3561377...",2022,24,Västerbottens län,2404,Vindeln,SWE,Kommun,2.871493e+09,None,SE1,None,1,SE1,"POLYGON ((701776.471 7184020.305, 703705.081 7...",6.802720e+08,2.871493e+09,2.369053e-01
141,"{ ""lon"": 18.460034437043642, ""lat"": 64.6536658...",2022,24,Västerbottens län,2481,Lycksele,SWE,Kommun,5.922552e+09,None,SE2,None,2,SE2,"POLYGON ((654702.974 7235008.153, 667174.689 7...",5.922552e+09,5.922552e+09,1.000000e+00
142,"{ ""lon"": 18.460034437043642, ""lat"": 64.6536658...",2022,24,Västerbottens län,2481,Lycksele,SWE,Kommun,5.922552e+09,None,SE1,None,1,SE1,"POLYGON ((654702.974 7235008.153, 667174.689 7...",2.863067e+08,5.922552e+09,4.834178e-02
143,"{ ""lon"": 12.576156942935084, ""lat"": 56.9696747...",2022,13,Hallands län,1382,Falkenberg,SWE,Kommun,1.837446e+09,None,SE4,None,4,SE4,"POLYGON ((376314.383 6345708.957, 375478.509 6...",7.190912e+08,1.837446e+09,3.913536e-01
144,"{ ""lon"": 12.576156942935084, ""lat"": 56.9696747...",2022,13,Hallands län,1382,Falkenberg,SWE,Kommun,1.837446e+09,None,SE3,None,3,SE3,"MULTIPOLYGON (((353149.116 6329952.028, 353261...",2.470152e+08,1.837446e+09,1.344339e-01
147,"{ ""lon"": 17.197751524765781, ""lat"": 61.2447592...",2022,21,Gävleborgs län,2182,Söderhamn,SWE,Kommun,2.298934e+09,None,SE2,None,2,SE2,"POLYGON ((614570.754 6770825.827, 614298.847 6...",1.163247e+09,2.298934e+09,5.059940e-01
148,"{ ""lon"": 17.197751524765781, ""lat"": 61.2447592...",2022,21,Gävleborgs län,2182,Söderhamn,SWE,Kommun,2.298934e+09,None,SE3,None,3,SE3,"POLYGON ((614298.847 6770417.571, 602559.206 6...",1.837966e+08,2.298934e+09,7.994863e-02
154,"{ ""lon"": 13.062021052914437, ""lat"": 57.3904298...",2022,14,Västra Götalands län,1465,Svenljunga,SWE,Kommun,9.903009e+08,None,SE4,None,4,SE4,"POLYGON ((391000.977 6345741.421, 390628.787 6...",1.278478e+08,9.903009e+08,1.291000e-01
155,"{ ""lon"": 13.062021052914437, ""lat"": 57.3904298...",2022,14,Västra Götalands län,1465,Svenljunga,SWE,Kommun,9.903009e+08,None,SE3,None,3,SE3,"POLYGON ((374302.585 6341304.392, 374367.541 6...",8.689436e+08,9.903009e+08,8.774541e-01
188,"{ ""lon"": 20.960227945494118, ""lat"": 64.1333090...",2022,24,Västerbottens län,2409,Robertsfors,SWE,Kommun,2.392110e+09,None,SE2,None,2,SE2,"POLYGON ((777128.943 7107569.338, 771105.437 7...",7.357080e+08,2.392110e+09,3.075561e-01
189,"{ ""lon"": 20.960227945494118, ""lat"": 64.1333090...",2022,24,Västerbottens län,2409,Robertsfors,SWE,Kommun,2.392110e+09,None,SE1,None,1,SE1,"POLYGON ((756331.308 7142530.437, 756677.969 7...",1.508250e+06,2.392110e+09,6.305104e-04
190,"{ ""lon"": 19.551584224557704, ""lat"": 64.9310967...",2022,24,Västerbottens län,2417,Norsjö,SWE,Kommun,1.935085e+09,None,SE2,None,2,SE2,"POLYGON ((720405.03 7189259.886, 712552.461 71...",3.886692e+08,1.935085e+09,2.008538e-01
191,"{ ""lon"": 19.551584224557704, ""lat"": 64.9310967...",2022,24,Västerbottens län,2417,Norsjö,SWE,Kommun,1.935085e+09,None,SE1,None,1,SE1,"POLYGON ((707654.729 7232830.942, 707937.699 7...",1.935085e+09,1.935085e+09,1.000000e+00
193,"{ ""lon"": 15.297311825967119, ""lat"": 61.1175666...",2022,20,Dalarnas län,2031,Rättvik,SWE,Kommun,2.145383e+09,None,SE2,None,2,SE2,"POLYGON ((504856.082 6816706.101, 508045.269 6...",1.279997e+08,2.145383e+09,5.966289e-02
194,"{ ""lon"": 15.297311825967119, ""lat"": 61.1175666...",2022,20,Dalarnas län,2031,Rättvik,SWE,Kommun,2.145383e+09,None,SE3,None,3,SE3,"POLYGON ((510886.101 6818961.925, 511529.698 6...",2.144006e+09,2.145383e+09,9.993581e-01
220,"{ ""lon"": 15.537519931233088, ""lat"": 61.8529027...",2022,21,Gävleborgs län,2161,Ljusdal,SWE,Kommun,5.638746e+09,None,SE2,None,2,SE2,"POLYGON ((474383.162 6843913.829, 474683.597 6...",5.541780e+09,5.638746e+09,9.828036e-01
221,"{ ""lon"": 15.537519931233088, ""lat"": 61.8529027...",2022,21,Gävleborgs län,2161,Ljusdal,SWE,Kommun,5.638746e+09,None,SE3,None,3,SE3,"MULTIPOLYGON (((474468.201 6844714.581, 474470...",5.513200e+08,5.638746e+09,9.777353e-02
230,"{ ""lon"": 17.28260609514232, ""lat"": 60.76483583...",2022,21,Gävleborgs län,2180,Gävle,SWE,Kommun,3.218111e+09,None,SE2,None,2,SE2,"POLYGON ((604944.878 6748170.694, 602874.369 6...",2.587235e+08,3.218111e+09,8.039607e-02
231,"{ ""lon"": 17.28260609514232, ""lat"": 60.76483583...",2022,21,Gävleborgs län,2180,Gävle,SWE,Kommun,3.218111e+09,None,SE3,None,3,SE3,"POLYGON ((647967.975 6733484.593, 638307.469 6...",2.608671e+09,3.218111e+09,8.106217e-01
234,"{ ""lon"": 20.445455629068199, ""lat"": 63.7592941...",2022,24,Västerbottens län,2480,Umeå,SWE,Kommun,5.312721e+09,None,SE2,None,2,SE2,"POLYGON ((736073.947 7053216.562, 735952.658 7...",1.968884e+09,5.312721e+09,3.705980e-01
235,"{ ""lon"": 20.445455629068199, ""lat"": 63.7592941...",2022,24,Västerbottens län,2480,Umeå,SWE,Kommun,5.312721e+09,None,SE1,None,1,SE1,"POLYGON ((746301.88 7133352.054, 747070.815 71...",1.267101e+08,5.312721e+09,2.385031e-02
244,"{ ""lon"": 16.735846587659644, ""lat"": 65.7216587...",2022,24,Västerbottens län,2422,Sorsele,SWE,Kommun,8.004603e+09,None,SE2,None,2,SE2,"POLYGON ((521756.43 7351478.401, 520374.953 73...",6.192302e+09,8.004603e+09,7.735926e-01
245,"{ ""lon"": 16.735846587659644, ""lat"": 65.7216587...",2022,24,Västerbottens län,2422,Sorsele,SWE,Kommun,8.004603e+09,None,SE1,None,1,SE1,"POLYGON ((580287.455 7324603.457, 590015.57 73...",1.130570e+09,8.004603e+09,1.412400e-01
258,"{ ""lon"": 18.726014051175667, ""lat"": 65.2368193...",2022,24,Västerbottens län,2418,Malå,SWE,Kommun,1.742559e+09,None,SE2,None,2,SE2,"POLYGON ((677189.345 7211955.205, 669124.437 7...",4.191937e+08,1.742559e+09,2.405622e-01
259,"{ ""lon"": 18.726014051175667, ""lat"": 65.2368193...",2022,24,Västerbottens län,2418,Malå,SWE,Kommun,1.742559e+09,None,SE1,None,1,SE1,"POLYGON ((649651.393 7247496.538, 652922.16 72...",1.735618e+09,1.742559e+09,9.960170e-01
265,"{ ""lon"": 15.15954805524575, ""lat"": 57.36706003...",2022,06,Jönköpings län,0685,Vetlanda,SWE,Kommun,1.605882e+09,None,SE4,None,4,SE4,"POLYGON ((530873.958 6351660.436, 530412.882 6...",5.077718e+08,1.605882e+09,3.161950e-01
266,"{ ""lon"": 15.15954805524575, ""lat"": 57.36706003...",2022,06,Jönköpings län,0685,Vetlanda,SWE,Kommun,1.605882e+09,None,SE3,None,3,SE3,"POLYGON ((489606.199 6365949.618, 489863.139 6...",6.097507e+08,1.605882e+09,3.796983e-01
270,"{ ""lon"": 16.573366404824458, ""lat"": 60.9246337...",2022,21,Gävleborgs län,2101,Ockelbo,SWE,Kommun,1.135405e+09,None,SE2,None,2,SE2,"POLYGON ((579063.264 6769556.693, 582106.194 6...",3.525773e+08,1.135405e+09,3.105299e-01
271,"{ ""lon"": 16.573366404824458, ""lat"": 60.9246337...",2022,21,Gävleborgs län,2101,Ockelbo,SWE,Kommun,1.135405e+09,None,SE3,None,3,SE3,"POLYGON ((602069.622 6765476.111, 602121.348 6...",1.135405e+09,1.135405e+09,1.000000e+00
287,"{ ""lon"": 16.614142211617324, ""lat"": 57.3979715...",2022,08,Kalmar län,0882,Oskarshamn,SWE,Kommun,2.279664e+09,None,SE4,None,4,SE4,"POLYGON ((588745.426 6332728.941, 588649.037 6...",3.683122e+08,2.279664e+09,1.615643e-01
288,"{ ""lon"": 16.614142211617324, ""lat"": 57.3979715...",2022,08,Kalmar län,0882,Oskarshamn,SWE,Kommun,2.279664e+09,None,SE3,None,3,SE3,"POLYGON ((562718.942 6360113.26, 561563.063 63...",7.102890e+08,2.279664e+09,3.115762e-01
295,"{ ""lon"": 13.138100590008859, ""lat"": 61.6460674...",2022,20,Dalarnas län,2039,Älvdalen,SWE,Kommun,7.186261e+09,None,SE2,None,2,SE2,"MULTIPOLYGON (((406907.945 6879988.914, 410453...",1.819455e+08,7.186261e+09,2.531852e-02
296,"{ ""lon"": 13.138100590008859, ""lat"": 61.6460674...",2022,20,Dalarnas län,2039,Älvdalen,SWE,Kommun,7.186261e+09,None,SE3,None,3,SE3,"POLYGON ((359574.984 6905582.036, 394367.023 6...",6.618361e+09,7.186261e+09,9.209742e-01
298,"{ ""lon"": 15.770269812809254, ""lat"": 61.3662269...",2022,21,Gävleborgs län,2121,Ovanåker,SWE,Kommun,2.025947e+09,None,SE2,None,2,SE2,"POLYGON ((516162.043 6810090.174, 511529.698 6...",1.649992e+09,2.025947e+09,8.144298e-01
299,"{ ""lon"": 15.770269812809254, ""lat"": 61.3662269...",2022,21,Gävleborgs län,2121,Ovanåker,SWE,Kommun,2.025947e+09,None,SE3,None,3,SE3,"POLYGON ((559540.425 6792529.531, 559932.387 6...",1.225892e+09,2.025947e+09,6.050956e-01